osx_image: xcode7.3
language: objective-c
script: xctool clean test -scheme SwiftRouter -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus"